name: OSM Pumps Harvester (dev)

on:
  workflow_dispatch: {}
#  repository_dispatch:
#    types: [pumps_cron]

jobs:
  pumps:
    environment: development
    runs-on: ubuntu-latest
    name: Aggregate pumps data from open street maps
    steps:
      - name: Get the source
        uses: actions/checkout@v3
      - name: build the harvester
        run: cd pumps-harvester/harvester && docker build --tag "${GITHUB_REPOSITORY}:${GITHUB_REF##*/}" .
      - name: run the harvester
        run: docker run -v /tmp:/tmp "${GITHUB_REPOSITORY}:${GITHUB_REF##*/}" /tmp/out.json
      - name: File output
        run: cat /tmp/out.json
