name: DWD Radolan Harvester

on:
  workflow_dispatch: {}
  repository_dispatch:
    types: [radolan_cron]
  # schedule:
  #   - cron: '30 5 * * *'

jobs:
  rain:
    environment: production
    runs-on: ubuntu-latest
    name: Aggregate rain data from DWD radolan
    steps:
      - name: Harvester
        uses: code-for-magdeburg/magdeburggiesst-dwd-harvester@port-to-md
        id: harvester
        with:
          PG_SERVER: ${{ vars.PG_SERVER }}
          PG_PORT: ${{ vars.PG_PORT }}
          PG_USER: ${{ vars.PG_USER }}
          PG_PASS: ${{ secrets.PG_PASS }}
          PG_DB: ${{ vars.PG_DB }}
          SUPABASE_PROJECT_ID: ${{ vars.SUPABASE_PROJECT_ID }}
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
          SUPABASE_BUCKET_NAME: ${{ vars.SUPABASE_DATA_ASSETS_BUCKET }}
          OUTPUT: 'True'
          LOGGING: 'INFO'
          MAPBOXUSERNAME: ${{ vars.MAPBOXUSERNAME }}
          MAPBOXTOKEN: ${{ secrets.MAPBOXTOKEN }}
          MAPBOXTILESET: ${{ vars.MAPBOXTILESET }}
          MAPBOXLAYERNAME: ${{ vars.MAPBOXLAYERNAME }}
