name: DWD Radolan Harvester

on:
  workflow_dispatch: {}
  repository_dispatch:
    types: [radolan_cron]

jobs:
  rain:
    environment: preview
    runs-on: ubuntu-latest
    name: Aggregate rain data from DWD radolan
    steps:
      - name: build the harvester
        run: cd dwd-harvester/harvester && docker build --tag code-for-magdeburg/magdeburggiesst-dwd-harvester:test .
      - name: run the harvester
        run: >
          docker run --env PG_SERVER=${{ vars.xxxPG_SERVER }} \
                     --env PG_DB=${{ vars.xxxPG_DB }} \
                     --env PG_PORT=${{ vars.xxxPG_PORT }} \
                     --env PG_USER=${{ vars.xxxPG_USER }} \
                     --env PG_PASS=${{ secrets.xxxPG_PASS }} \
                     --env SUPABASE_PROJECT_ID=${{ vars.xxxSUPABASE_PROJECT_ID }} \
                     --env SUPABASE_ACCESS_TOKEN=${{ secrets.xxxSUPABASE_ACCESS_TOKEN }} \
                     --env SUPABASE_BUCKET_NAME=${{ vars.xxxSUPABASE_DATA_ASSETS_BUCKET }} \
                     --env MAPBOXTOKEN=${{ secrets.xxxMAPBOXTOKEN }} \
                     --env MAPBOXUSERNAME=${{ vars.xxxMAPBOXUSERNAME }} \
                     --env MAPBOXTILESET=${{ vars.xxxMAPBOXTILESET }} \
                     --env MAPBOXLAYERNAME=${{ vars.xxxMAPBOXLAYERNAME }} \
                     --env LOGGING='INFO' \
                     --env OUTPUT=True \
                     --network host \
                     code-for-magdeburg/magdeburggiesst-dwd-harvester:test  
